spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:questify_db}
    username: ${POSTGRES_USER:questify}
    password: ${POSTGRES_PASSWORD:questify}
  jpa:
    hibernate:
      ddl-auto: update   # Sprint 0: crée/maj les tables à partir des @Entity
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
